#Container Setup for Development
  version: '2'

  # Named volumes
  volumes:
    #Redis Data
    meu-otp-redis-data:
      driver: local

  services:
    # Caching
    cache:
      image: redis:4.0
      container_name: meu-otp-redis
      command: --appendonly yes
      volumes:
        - meu-otp-redis-data:/data
      ports:
        - "6379:6379"

    app:
      image: ambientum/node:11
      container_name: meu-otp-app
      command: tail -f /dev/null
      environment:
        - NODE_ENV=local
      ports:
        - 3000:3000
      volumes:
        - .:/var/www/app

    proxy:
      container_name: meu-otp-proxy
      build:
        context: ./docker
        dockerfile: Proxy.Dockerfile
      volumes:
        - ./dist:/var/www/app
      ports:
        - 80:80
